### ISSUE TITLE
Duplicate Parameter Destination in TableService throws Exception

### ISSUE THREAD

**Issue by jpkempkes** [FantaStudio/OSRMLib#1]
https://github.com/FantaStudio/OSRMLib/blob/94c0ac1263fff279ed265a65ca9f885714dc5eb3/OSRMLib/OSRMServices/TableService.cs#L74

This if clause is repeated and adds the parameter twice to the call. That leads to an exceptional fail.

**Comment by FantaStudio** [comment]
Oh, thanks)
didn't notice it
